"""Shared constants for the OKX Long Bot clean rebuild v116."""

MODE_NORMAL_LONG = "NORMAL_LONG"
MODE_STRONG_LONG_ONLY = "STRONG_LONG_ONLY"
MODE_BLOCK_LONGS = "BLOCK_LONGS"
MODE_RECOVERY_LONG = "RECOVERY_LONG"

MARKET_MODES = (
    MODE_NORMAL_LONG,
    MODE_STRONG_LONG_ONLY,
    MODE_BLOCK_LONGS,
    MODE_RECOVERY_LONG,
)

PERIOD_SINCE_START = "since_start"
PERIOD_LAST_7D = "last_7d"
PERIOD_TODAY = "today"
PERIOD_LAST_1H = "last_1h"

REPORT_PERIOD_ORDER = (
    PERIOD_SINCE_START,
    PERIOD_LAST_7D,
    PERIOD_TODAY,
    PERIOD_LAST_1H,
)

TP1_CLOSE_PCT = 40.0
TP2_CLOSE_PCT = 40.0
RUNNER_CLOSE_PCT = 20.0
TRAILING_STOP_AFTER_TP2_PCT = 2.0
BREAKEVEN_BUFFER_PCT = 0.10
DEFAULT_LEVERAGE = 15
RECOVERY_WINDOW_MINUTES = 90
MAX_RECOVERY_TRADES_PER_CYCLE = 3
MAX_BLOCK_EXCEPTION_TRADES_PER_CYCLE = 3
MAX_EXECUTION_POSITIONS = 10
LEVERAGE_NOTE_AR = "⚡ جميع نسب الأداء محسوبة على رافعة 15x"


MODE_COLOR_EMOJI = {
    MODE_NORMAL_LONG: "🟢",
    MODE_STRONG_LONG_ONLY: "🟨",
    MODE_BLOCK_LONGS: "🔴",
    MODE_RECOVERY_LONG: "🔵",
}

MODE_TITLE_MAP = {
    MODE_NORMAL_LONG: "🟢 Market Mode: NORMAL_LONG",
    MODE_STRONG_LONG_ONLY: "🟨 Market Mode: STRONG_LONG_ONLY",
    MODE_BLOCK_LONGS: "🔴 Market Mode: BLOCK_LONGS",
    MODE_RECOVERY_LONG: "🔵 Market Mode: RECOVERY_LONG",
}

MODE_EXECUTION_HEADER_MAP = {
    MODE_NORMAL_LONG: "🚀🟢 EXECUTION PRIORITY",
    MODE_STRONG_LONG_ONLY: "🚀🟨 STRONG EXECUTION",
    MODE_BLOCK_LONGS: "🚀🔴 BLOCK EXCEPTION EXECUTION",
    MODE_RECOVERY_LONG: "🚀🔵 RECOVERY EXECUTION",
}


MODE_NORMAL_SIGNAL_HEADER_MAP = {
    MODE_NORMAL_LONG: "📈🟢 LONG SIGNAL",
    MODE_STRONG_LONG_ONLY: "📈🟨 LONG SIGNAL",
    MODE_BLOCK_LONGS: "📈🔴 LONG SIGNAL",
    MODE_RECOVERY_LONG: "📈🔵 LONG SIGNAL",
}
